@extends('layout')
@section('content')
<div class="page-heading"><div><h1>Dokümanlar</h1><p class="muted">Şirket belgeleri, güncel sürümleri ve erişim izinleri tek yerde.</p></div>@can('create',\App\Models\Document::class)<a class="button primary" href="{{ route('documents.create') }}">+ Yeni Doküman</a>@endcan</div>
<form method="get" class="document-search"><label for="document-q">Belgelerde ara</label><div class="action-row"><input id="document-q" name="q" value="{{ $q }}" maxlength="100" placeholder="Ad, kategori, açıklama, dosya, yükleyen veya tarih"><input type="hidden" name="category" value="{{ request('category') }}"><input type="hidden" name="archived" value="{{ request('archived') }}"><button>Ara</button><a href="{{ route('documents.index') }}">Temizle</a></div><small>Belge tarihi: GG.AA.YYYY veya YYYY-AA-GG. Yalnız görmeye yetkili olduğunuz belgeler aranır.</small></form>
<nav class="document-tabs" aria-label="Belge durumu"><a href="{{ route('documents.index') }}" @if(!request('archived')) aria-current="page" @endif>Güncel belgeler</a><a href="{{ route('documents.index',['archived'=>1]) }}" @if(request('archived')) aria-current="page" @endif>Arşivlenenler</a></nav>
<div class="document-layout"><aside class="card" aria-label="Doküman kategorileri"><h2>Kategoriler</h2><a href="{{ route('documents.index',array_filter(['archived'=>request('archived')])) }}">Tüm kategoriler</a>@include('documents.tree',['nodes'=>$tree])</aside><section aria-label="Belgeler">@if(request('archived'))<p class="hint">{{ config('documents.retention') }} Arşivdeki dosyalar geri getirilmeden açılamaz.</p>@endif
@forelse($documents as $document)@php($version=$document->latestVersion)<article class="card document-row"><div class="document-file-icon" aria-hidden="true">{{ strtoupper($version->extension) }}</div><div class="document-row-body"><div class="document-title"><h2><a href="{{ route('documents.show',$document->id) }}">{{ $document->name }}</a></h2><span class="badge">{{ \App\Models\Document::VISIBILITIES[$document->visibility] }}</span></div><p>{{ $document->category->name }} · <strong>v{{ $version->number }}</strong> · Belge: {{ $document->document_date->format('d.m.Y') }}</p><p class="muted">{{ $version->uploader->name }} · Yüklendi: {{ $version->created_at->timezone('Europe/Istanbul')->format('d.m.Y') }} · {{ number_format($version->size/1024,1,',','.') }} KB</p>@if($document->expires_at)<p class="{{ $document->expires_at->endOfDay()->isPast() ? 'document-expired' : 'muted' }}">Geçerlilik: {{ $document->expires_at->format('d.m.Y') }}{{ $document->expires_at->endOfDay()->isPast() ? ' · Süresi doldu' : '' }}</p>@endif @include('documents.file-actions')<p><a href="{{ route('documents.show',$document->id) }}">Ayrıntılar ve geçmiş →</a></p></div></article>@empty<div class="card"><h2>Bu görünümde belge yok.</h2><p>Arama veya kategori filtresini değiştirebilirsiniz. Yeni belge eklediğinizde güncel sürüm burada, eski sürümler belgenin Geçmiş bölümünde görünür.</p></div>@endforelse @include('partials.pagination',['records'=>$documents])</section></div>
@if(\App\Models\Document::permits(auth()->user(),'manage_categories'))<details class="panel"><summary>Kategori / alt kategori ekle</summary><form method="post" action="{{ route('document-categories.store') }}">@csrf<label for="category-name">Kategori adı</label><input id="category-name" name="name" required maxlength="120"><label for="parent">Üst kategori</label><select id="parent" name="parent_id"><option value="">Ana kategori</option>@include('documents.category-options',['nodes'=>$tree,'depth'=>0,'selected'=>null])</select><p class="muted">Kategori başlıkları tüm CRM kullanıcılarına görünür; başlığa kişisel veya gizli bilgi yazmayın.</p><button>Kategoriyi ekle</button></form></details>@endif
@endsection
