@extends('layout')
@section('content')
<a href="{{ route('documents.index') }}">← Dokümanlar</a><div class="page-heading"><div><h1>{{ $document->name }}</h1><p>{{ $document->category->name }} · <span class="badge">{{ \App\Models\Document::VISIBILITIES[$document->visibility] }}</span>@if($document->trashed()) <span class="badge">Arşivlendi</span>@endif</p></div>@can('update',$document)<a class="button" href="{{ route('documents.edit',$document->id) }}">Belge bilgilerini düzenle</a>@endcan</div>
@php($version=$document->latestVersion)
<section class="card"><h2>Güncel sürüm · v{{ $version->number }}</h2><p>{{ $version->original_name }} · {{ number_format($version->size/1024,1,',','.') }} KB</p><p>Yükleyen: {{ $version->uploader->name }} · {{ $version->created_at->timezone('Europe/Istanbul')->format('d.m.Y H:i') }}</p><p>Belge tarihi: {{ $document->document_date->format('d.m.Y') }} @if($document->expires_at) · Geçerlilik: {{ $document->expires_at->format('d.m.Y') }} @endif</p><p class="preserve-lines">{{ $document->description }}</p>@if($version->note)<p class="preserve-lines">Sürüm notu: {{ $version->note }}</p>@endif @include('documents.file-actions')
<details><summary>Kimler görebilir?</summary><p>Belge sahibi: {{ $document->owner->name }}</p>@if($document->visibility==='internal')<p>Tüm aktif ve belge görüntüleme yetkili CRM kullanıcıları.</p>@else<p>İzinli kullanıcılar: {{ $users->whereIn('id',$document->allowed_users)->pluck('name')->join(', ') ?: 'Ek kullanıcı seçilmedi' }}</p><p>İzinli roller: {{ collect($roles)->only($document->allowed_roles)->values()->join(', ') ?: 'Rol seçilmedi' }}</p>@endif<p class="muted">Eski sürümler de bu izinleri kullanır. Yönetici rolü tek başına tüm özel belgeleri açmaz.</p></details></section>
@can('manageVersions',$document)<details class="panel"><summary>Yeni Sürüm Yükle</summary><form method="post" enctype="multipart/form-data" action="{{ route('documents.versions',$document->id) }}">@csrf<input type="hidden" name="revision" value="{{ $document->revision }}">@include('documents.file-fields')<button class="primary">Yeni sürümü kaydet</button></form></details>@endcan
<details class="panel" @if(request('page')) open @endif><summary>Geçmiş · {{ $history->total() }} eski sürüm</summary>@forelse($history as $version)<article class="document-history"><h3>v{{ $version->number }} · {{ $version->created_at->timezone('Europe/Istanbul')->format('d.m.Y H:i') }}</h3><p>{{ $version->uploader->name }} · {{ $version->original_name }} · {{ number_format($version->size/1024,1,',','.') }} KB</p><p class="preserve-lines">{{ $version->note }}</p>@include('documents.file-actions')</article>@empty<p>Henüz eski sürüm yok.</p>@endforelse @include('partials.pagination',['records'=>$history])</details>
@can('managePermissions',$document)<details class="panel"><summary>Erişim izinlerini yönet</summary><form method="post" action="{{ route('documents.access',$document->id) }}">@csrf @method('PUT')<input type="hidden" name="revision" value="{{ $document->revision }}">@include('documents.access-fields')<button>İzinleri kaydet</button></form></details>@endcan
<details class="panel"><summary>İşlem geçmişi · Son 30 işlem</summary><ul>@foreach($events as $event)<li>{{ \Carbon\Carbon::parse($event->created_at)->timezone('Europe/Istanbul')->format('d.m.Y H:i') }} · {{ $event->name }} · {{ ['created'=>'Doküman oluşturuldu','file_uploaded'=>'Dosya yüklendi','version_uploaded'=>'Yeni sürüm yüklendi','viewed'=>'Belge görüntülendi','previewed'=>'Dosya önizlendi','downloaded'=>'Dosya indirildi','permissions_changed'=>'İzinler değiştirildi','metadata_changed'=>'Belge bilgileri değiştirildi','archived'=>'Arşivlendi','restored'=>'Geri getirildi'][$event->action] ?? $event->action }} @if($event->version) · v{{ $event->version }} @endif
@if($event->action==='metadata_changed')<details><summary>Önceki bilgiler</summary>@php($before=json_decode($event->details,true)['before'] ?? [])<dl>@foreach(['name'=>'Doküman adı','category_id'=>'Kategori','description'=>'Açıklama','document_date'=>'Belge tarihi','expires_at'=>'Geçerlilik tarihi'] as $field=>$label)<dt>{{ $label }}</dt><dd class="preserve-lines">{{ $field==='category_id' ? ($categories->firstWhere('id',$before[$field] ?? null)?->name ?? '—') : ($before[$field] ?? '—') }}</dd>@endforeach</dl></details>@endif</li>@endforeach</ul></details>
@can('delete',$document)<details class="panel"><summary>Belgeyi arşivle</summary><p>{{ config('documents.retention') }}</p><form method="post" action="{{ route('documents.destroy',$document->id) }}">@csrf @method('DELETE')<input type="hidden" name="revision" value="{{ $document->revision }}"><button>Arşivlemeyi onayla</button></form></details>@endcan
@can('restore',$document)<section class="panel"><h2>Arşivlenen belge</h2><p>{{ config('documents.retention') }}</p><form method="post" action="{{ route('documents.restore',$document->id) }}">@csrf<input type="hidden" name="revision" value="{{ $document->revision }}"><button>Belgeyi geri getir</button></form></section>@endcan
@endsection
