<?php

use App\Http\Controllers\ActivationController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DocumentCategoryController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\KozaController;
use App\Http\Controllers\MatchingController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\SupplyCategoryController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/home');
Route::middleware('guest')->group(function () {
    Route::get('/activate', [ActivationController::class, 'create'])->name('activation.create');
    Route::post('/activate', [ActivationController::class, 'store'])->middleware('throttle:activation')->name('activation.store');
    Route::get('/login', [SessionController::class, 'create'])->name('login');
    Route::post('/login', [SessionController::class, 'store'])->middleware('throttle:login');
});
Route::middleware(['auth', 'active'])->group(function () {
    Route::post('/document-categories', [DocumentCategoryController::class, 'store'])->name('document-categories.store');
    Route::get('/documents', [DocumentController::class, 'index'])->name('documents.index');
    Route::get('/documents/create', [DocumentController::class, 'create'])->name('documents.create');
    Route::post('/documents', [DocumentController::class, 'store'])->name('documents.store');
    Route::get('/documents/{document}', [DocumentController::class, 'show'])->whereNumber('document')->name('documents.show');
    Route::get('/documents/{document}/edit', [DocumentController::class, 'edit'])->whereNumber('document')->name('documents.edit');
    Route::put('/documents/{document}', [DocumentController::class, 'update'])->whereNumber('document')->name('documents.update');
    Route::put('/documents/{document}/access', [DocumentController::class, 'access'])->whereNumber('document')->name('documents.access');
    Route::post('/documents/{document}/versions', [DocumentController::class, 'version'])->whereNumber('document')->name('documents.versions');
    Route::get('/documents/{document}/versions/{version}/download', [DocumentController::class, 'file'])->whereNumber(['document', 'version'])->name('documents.download');
    Route::get('/documents/{document}/versions/{version}/preview', [DocumentController::class, 'file'])->whereNumber(['document', 'version'])->name('documents.preview');
    Route::delete('/documents/{document}', [DocumentController::class, 'destroy'])->whereNumber('document')->name('documents.destroy');
    Route::post('/documents/{document}/restore', [DocumentController::class, 'restore'])->whereNumber('document')->name('documents.restore');

    Route::get('/home', [KozaController::class, 'home'])->name('workspace.home');
    Route::prefix('koza/api')->middleware('throttle:120,1')->group(function () {
        Route::get('/bootstrap', [KozaController::class, 'bootstrap']);
        Route::get('/records', [KozaController::class, 'index']);
        Route::post('/records', [KozaController::class, 'store']);
        Route::get('/records/{record}', [KozaController::class, 'show'])->whereNumber('record');
        Route::put('/records/{record}', [KozaController::class, 'update'])->whereNumber('record');
        Route::post('/records/{record}/actions', [KozaController::class, 'action'])->whereNumber('record');
        Route::get('/records/{record}/history/{event}', [KozaController::class, 'history'])->whereNumber(['record', 'event']);
        Route::get('/records/{record}/trace', [KozaController::class, 'trace'])->whereNumber('record');
        Route::put('/preferences', [KozaController::class, 'preferences']);
        Route::post('/companies', [KozaController::class, 'company']);
        Route::put('/companies/{company}', [KozaController::class, 'company']);
        Route::get('/settings', [KozaController::class, 'settings']);
        Route::put('/settings/policy', [KozaController::class, 'policy']);
        Route::put('/settings/access', [KozaController::class, 'grant']);
        Route::get('/documents', [KozaController::class, 'documents']);
        Route::post('/documents', [KozaController::class, 'upload']);
        Route::post('/documents/{document}/versions', [KozaController::class, 'upload'])->whereNumber('document');
        Route::post('/ask', [KozaController::class, 'ask']);
        Route::get('/analytics', [KozaController::class, 'analytics']);
        Route::get('/export', [KozaController::class, 'export']);
    });
    Route::get('/activities', [WorkspaceController::class, 'activities'])->name('workspace.activities');
    Route::get('/workspace/{module}', [WorkspaceController::class, 'module'])->name('workspace.module');
    Route::post('/companies/{company}/matching', [MatchingController::class, 'existing'])->name('matching.existing');
    Route::post('/matching/cancel', [MatchingController::class, 'cancel'])->name('matching.cancel');
    Route::post('/matching/aliases', [MatchingController::class, 'alias'])->name('matching.alias');
    Route::get('/matching', [MatchingController::class, 'index'])->name('matching.index');
    Route::post('/matching/decide', [MatchingController::class, 'decide'])->name('matching.decide')->block(10, 10);
    Route::post('/matching/settings', [MatchingController::class, 'settings'])->name('matching.settings');
    Route::post('/matching/{decision}/revoke', [MatchingController::class, 'revoke'])->name('matching.revoke');
    Route::resource('contacts', ContactController::class)->only(['index', 'create', 'store', 'show']);
    Route::post('/logout', [SessionController::class, 'destroy'])->name('logout');
    Route::post('/supply-categories', [SupplyCategoryController::class, 'store'])->name('supply-categories.store');
    Route::get('/companies/{company}/history', [CompanyController::class, 'history'])->name('companies.history');
    Route::resource('companies', CompanyController::class);
    Route::get('/projects', [ProjectController::class, 'index'])->name('projects.index');
    Route::get('/companies/{company}/projects/create', [ProjectController::class, 'create'])->name('projects.create');
    Route::post('/companies/{company}/projects', [ProjectController::class, 'store'])->name('projects.store');
    Route::get('/projects/{project}', [ProjectController::class, 'show'])->name('projects.show');
    Route::get('/projects/{project}/edit', [ProjectController::class, 'edit'])->name('projects.edit');
    Route::put('/projects/{project}', [ProjectController::class, 'update'])->name('projects.update');
    Route::get('/projects/{project}/history', [ProjectController::class, 'history'])->name('projects.history');
    Route::get('/companies/{company}/activities/create', [ActivityController::class, 'create'])->name('activities.create');
    Route::post('/companies/{company}/activities', [ActivityController::class, 'store'])->name('activities.store');
    Route::get('/activities/{activity}/edit', [ActivityController::class, 'edit'])->name('activities.edit');
    Route::put('/activities/{activity}', [ActivityController::class, 'update'])->name('activities.update');
    Route::get('/activities/{activity}/history', [ActivityController::class, 'history'])->name('activities.history');
});
